# Table 2

Audio-visual video classification results on VGGSounder. We report multi-label classification metrics (subset accuracy, F1- score, Hit accuracy, modality confusion μ) on background music free subset for audio- a(A), visual - v(V), audio-visual - av(AV), audio-only - a(A¬V) and video-only - v(V¬A) inputs. The embedding models CAV-MAE, DeepAVFusion, and Equi-AV were finetuned on the VGGSound training set. We report metrics for k = 1 here and for other k in Appendix D. The closed sourced multi-modal foundation models Gemini and open-sourced models use a zero-shot evaluation protocol and LLM-assisted protocol respectively.

In [1]:
from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

vggsounder = VGGSounder()
main_table = benchmark(
    models_path="../../supplimentary/models-results",
    display_names = {
        "cav-mae": "CAV-MAE",
        "deepavfusion": "DeepAVFusion",
        "equiav": "Equi-AV",
        "avsiam": "AV-Siam",
        "gemini-1.5-flash": "Gemini 1.5 Flash",
        "gemini-1.5-pro": "Gemini 1.5 Pro",
        "gemini-2.0-flash": "Gemini 2.0 Flash",
        "video-llama-2-av": "VideoLLaMA 2",
        "unified-io-2": "Unified-IO 2",
        "pandagpt": "PandaGPT",
        "ola": "OLA",
    },
    metrics=[
        ("accuracy", ["a", "v", "av"]), 
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    vggsounder=vggsounder
)

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

In [2]:
print(main_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 13.19 & 19.23 & 24.49 & 34.47 & 34.91 & 42.62 & 13.94 & 19.00 & 62.30 & 53.44 & 64.17 & 3.96 & 6.01 & 0.91 \\
DeepAVFusion & 10.19 & 11.10 & 21.53 & 25.31 & 21.29 & 37.35 & 10.37 & 10.55 & 45.77 & 32.61 & 56.27 & 4.10 & 3.73 & 0.19 \\
Equi-AV & 11.60 & 10.52 & 20.00 & 29.39 & 20.42 & 34.69 & 12.55 & 10.65 & 53.12 & 31.26 & 52.24 & 7.95 & 6.91 & 1.58 \\
AV-Siam & 12.79 & 19.75 & 22.83 & 33.30 & 35.41 & 39.43 & 12.90 & 18.21 & 60.18 & 54.20 & 59.36 & 10.30 & 8.69 & 3.75 \\
Gemini 1.5 Flash & 1.78 & 14.44 & 16.44 & 14.49 & 36.98 & 42.52 & 15.61 & 21.61 & 32.73 & 47.36 & 59.10 & 14.36 & 4.10 & 1.47 \\
Gemini 1.5 Pro & 3.05 & 20.86 & 22.53 & 19.26 & 49.73 & 53.74 & 17.73 & 22.90 & 35.03 & 69.23 & 75.42 & 3.07 & 4.23 & 0.71 \\
Gemini 2.0 Flash & 1.85 & 12.54 & 12.69 & 11.80 & 34.08 & 36.45 & 6.19 & 18.90 & 18.51 & 43.83 & 47.72 & 2.58 & 5.25 & 1.03 \\
VideoLLaMA 2 & 12.86 & 19.85 & 24.47 & 38.87 & 47.82 & 52.35 & 20.34 & 28.08 & 58.91 & 52.02 & 59.80 & 14.34 & 5.43 & 3.19 \\
Unified-IO 2 & 11.94 & 11.56 & 25.61 & 35.31 & 27.92 & 48.89 & 21.38 & 16.53 & 54.39 & 31.05 & 65.11 & 10.20 & 4.67 & 1.92 \\
PandaGPT & 3.19 & 4.19 & 5.46 & 18.73 & 18.56 & 20.85 & 16.82 & 14.40 & 21.08 & 17.01 & 18.82 & 10.06 & 6.63 & 3.22 \\
OLA & 14.11 & 8.69 & 18.19 & 47.70 & 24.85 & 46.48 & 40.44 & 13.45 & 59.05 & 24.57 & 51.51 & 17.07 & 6.32 & 2.90 \\
\bottomrule
\end{tabular}

# Table 3
Difference between labels that contain confounding factors such as "background music" and that do not contain.

In [3]:
from vggsounder.benchmark import compute_all_results, get_metric_dataframe, select_metrics
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
vggsounder = VGGSounder(csv_path=csv_path)

# background_music
vggsounder.set_meta_filters(background_music=True)
background_music_ids = [video.video_id for video in vggsounder]

background_music_only_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=background_music_ids,
    dataset_path=csv_path
)

# no background music
vggsounder.set_meta_filters(background_music=False)
no_background_music_ids = [video.video_id for video in vggsounder]

no_background_music_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=no_background_music_ids,
    dataset_path=csv_path
)

# voice over
vggsounder.set_meta_filters(voice_over=True)
voice_over_ids = [video.video_id for video in vggsounder]

voice_over_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=voice_over_ids,
    dataset_path=csv_path
)

# no voice over
vggsounder.set_meta_filters(voice_over=False)
no_voice_over_ids = [video.video_id for video in vggsounder]

no_voice_over_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=no_voice_over_ids,
    dataset_path=csv_path
)

# static image
vggsounder.set_meta_filters(static_image=True)
static_image_ids = [video.video_id for video in vggsounder]

static_image_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=static_image_ids,
    dataset_path=csv_path
)

# no static image
vggsounder.set_meta_filters(static_image=False)
no_static_image_ids = [video.video_id for video in vggsounder]

no_static_image_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=no_static_image_ids,
    dataset_path=csv_path
)

# neither
vggsounder.set_meta_filters(
    static_image=False, 
    voice_over=False, 
    background_music=False
)
neither_ids = [video.video_id for video in vggsounder]

neither_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=neither_ids,
    dataset_path=csv_path
)

# main table -- vggsounder + background music
either_of_confounder = list(set(background_music_ids + voice_over_ids + static_image_ids))
main_table_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=either_of_confounder,
    dataset_path=csv_path
)

  0%|          | 0/11 [00:00<?, ?it/s]

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

  0%|          | 0/11 [00:00<?, ?it/s]

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

  0%|          | 0/11 [00:00<?, ?it/s]

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

  0%|          | 0/11 [00:00<?, ?it/s]

In [4]:
main_table_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    dataset_path=csv_path
)

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

In [5]:
# background music only
background_music_only_df = get_metric_dataframe(background_music_only_results)
background_music_only_table = select_metrics(background_music_only_df, [("f1", ["a", "v", "av"])], display_names=display_names)

# no background music
no_background_music_df = get_metric_dataframe(no_background_music_results)
no_background_music_table = select_metrics(no_background_music_df, [("f1", ["a", "v", "av"])], display_names=display_names)

# voice over only
voice_over_df = get_metric_dataframe(voice_over_results)
voice_over_table = select_metrics(voice_over_df, [("f1", ["a"])], display_names=display_names)

# no voice over
no_voice_over_df = get_metric_dataframe(no_voice_over_results)
no_voice_over_table = select_metrics(no_voice_over_df, [("f1", ["a"])], display_names=display_names)

# static image only
static_image_df = get_metric_dataframe(static_image_results)
static_image_table = select_metrics(static_image_df, [("f1", ["a", "v"])], display_names=display_names)
static_image_accuracy_table = select_metrics(static_image_df, [("accuracy", ["a", "v"])], display_names=display_names)

# no static image
no_static_image_df = get_metric_dataframe(no_static_image_results)
no_static_image_table = select_metrics(no_static_image_df, [("f1", ["a", "v"])], display_names=display_names)
no_static_image_accuracy_table = select_metrics(no_static_image_df, [("accuracy", ["a", "v"])], display_names=display_names)

# neither
neither_df = get_metric_dataframe(neither_results)
neither_table = select_metrics(neither_df, [("f1", ["a", "v", "av"])], display_names=display_names)

# main table -- vggsounder + background music
main_table_df = get_metric_dataframe(main_table_results)
main_table_table = select_metrics(main_table_df, [("f1", ["a", "v", "av"])], display_names=display_names)

In [6]:
import pandas as pd

# final diff table 
diff_tables = [
    background_music_only_table - no_background_music_table,
    voice_over_table - no_voice_over_table,
    static_image_table - no_static_image_table,
    static_image_accuracy_table,
    no_static_image_accuracy_table,
    main_table_table - neither_table,
]

diff_tables = pd.concat(diff_tables, axis=1)
diff_tables

metric                   f1                                           \
modality                  a         v        av          a         a
CAV-MAE           -3.434171 -3.595847 -4.005153  -8.186111  4.747236
DeepAVFusion      -3.650865 -4.861405 -4.272057  -9.051576  4.334950
Equi-AV           -4.066210 -2.534618 -2.541157  -7.131573  4.258020
AV-Siam           -3.745411 -4.387541 -5.098110  -7.961802  5.226650
Gemini 1.5 Flash  -1.173969 -2.392415 -4.173242  17.251452 -5.277933
Gemini 1.5 Pro    -1.861540 -3.672653 -5.799092  18.163835 -4.899848
Gemini 2.0 Flash  -0.466296 -1.918562 -3.471032   0.195220  1.962523
VideoLLaMA 2      -2.431225 -4.620166 -5.524720  -3.969227  4.224274
Unified-IO 2      -6.405868  1.151202 -4.179440  -4.981597  1.881191
PandaGPT          -5.977940 -0.925743 -2.745251   3.916475 -3.682674
OLA              -11.837778  0.625064 -2.873214  10.091284 -8.235859

metric                       accuracy                                   \
modality                 v          a          v          a          v
CAV-MAE          -7.392629  22.132616  19.480519  11.981861  19.210926
DeepAVFusion     -4.878302  15.981308  10.958904   9.300612  10.807610
Equi-AV          -5.991801  18.996416  10.389610  10.493871  10.447648
AV-Siam          -6.851267  22.043011  19.805195  11.570892  19.522003
Gemini 1.5 Flash -7.313747   1.433692  13.474026   1.679303  14.393020
Gemini 1.5 Pro   -6.864390   2.329749  22.077922   2.869695  20.796662
Gemini 2.0 Flash -7.108631   3.853047  10.876623   1.530504  12.397572
VideoLLaMA 2     -9.516781  18.996416  18.181818  12.038546  19.704097
Unified-IO 2     -6.188150  17.921147   9.577922  10.876497  11.995448
PandaGPT         -4.864189   3.315412   4.870130   2.905123   4.241275
OLA              -5.401295  14.874552   8.603896  12.881740   8.892261

metric                  f1
modality                 a         v        av
CAV-MAE          -0.994139 -1.268619 -1.239505
DeepAVFusion     -1.265321 -1.004223 -1.355490
Equi-AV          -0.965314 -0.965586 -0.886427
AV-Siam          -1.012830 -1.339200 -1.385457
Gemini 1.5 Flash  1.402029 -1.095318 -1.622232
Gemini 1.5 Pro    1.644341 -0.886940 -1.090824
Gemini 2.0 Flash -0.029539 -1.063979 -1.217105
VideoLLaMA 2     -0.466918 -1.256753 -1.328538
Unified-IO 2     -1.069651 -0.150157 -1.170446
PandaGPT         -0.604699 -0.153187 -0.655662
OLA              -0.795312 -0.128429 -0.063080

In [7]:
print(diff_tables.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{6}{r}{f1} & \multicolumn{4}{r}{accuracy} & \multicolumn{3}{r}{f1} \\
modality & a & v & av & a & a & v & a & v & a & v & a & v & av \\
\midrule
CAV-MAE & -3.43 & -3.60 & -4.01 & -8.19 & 4.75 & -7.39 & 22.13 & 19.48 & 11.98 & 19.21 & -0.99 & -1.27 & -1.24 \\
DeepAVFusion & -3.65 & -4.86 & -4.27 & -9.05 & 4.33 & -4.88 & 15.98 & 10.96 & 9.30 & 10.81 & -1.27 & -1.00 & -1.36 \\
Equi-AV & -4.07 & -2.53 & -2.54 & -7.13 & 4.26 & -5.99 & 19.00 & 10.39 & 10.49 & 10.45 & -0.97 & -0.97 & -0.89 \\
AV-Siam & -3.75 & -4.39 & -5.10 & -7.96 & 5.23 & -6.85 & 22.04 & 19.81 & 11.57 & 19.52 & -1.01 & -1.34 & -1.39 \\
Gemini 1.5 Flash & -1.17 & -2.39 & -4.17 & 17.25 & -5.28 & -7.31 & 1.43 & 13.47 & 1.68 & 14.39 & 1.40 & -1.10 & -1.62 \\
Gemini 1.5 Pro & -1.86 & -3.67 & -5.80 & 18.16 & -4.90 & -6.86 & 2.33 & 22.08 & 2.87 & 20.80 & 1.64 & -0.89 & -1.09 \\
Gemini 2.0 Flash & -0.47 & -1.92 & -3.47 & 0.20 & 1.96 & -7.11 & 3.85 & 10.88 & 1.53 & 12.40 & -0.03 & -1.06 & -1.22 \\
VideoLLaMA 2 & -2.43 & -4.62 & -5.52 & -3.97 & 4.22 & -9.52 & 19.00 & 18.18 & 12.04 & 19.70 & -0.47 & -1.26 & -1.33 \\
Unified-IO 2 & -6.41 & 1.15 & -4.18 & -4.98 & 1.88 & -6.19 & 17.92 & 9.58 & 10.88 & 12.00 & -1.07 & -0.15 & -1.17 \\
PandaGPT & -5.98 & -0.93 & -2.75 & 3.92 & -3.68 & -4.86 & 3.32 & 4.87 & 2.91 & 4.24 & -0.60 & -0.15 & -0.66 \\
OLA & -11.84 & 0.63 & -2.87 & 10.09 & -8.24 & -5.40 & 14.87 & 8.60 & 12.88 & 8.89 & -0.80 & -0.13 & -0.06 \\
\bottomrule
\end{tabular}

# Figure 9 (Table)
Performance of state-of-the-art models on VGGSound.

In [8]:
import pickle as pk
from vggsounder.benchmark import benchmark, get_metric_dataframe, select_metrics
from vggsounder.labels import VGGSounder


models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
vggsounder = VGGSounder(csv_path=csv_path)

vggsound_results = pk.load(open("precomputed_results/vggsound_results.pkl", "rb"))
table_9_df = get_metric_dataframe(vggsound_results, modalities=["a", "v", "av"])
table_9 = select_metrics(
    table_9_df, 
    [
        ("accuracy", ["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ], 
    display_names=display_names
)
table_9

metric             accuracy                               mu            \
modality                  a          v         av          a         v
CAV-MAE           59.050887  45.565195  65.078337   4.713194  4.836204
DeepAVFusion      40.824576  27.243331  53.098895   4.176772  3.172999
Equi-AV           46.678752  24.841383  50.077690   6.907937  5.509517
AV-Siam           56.907937  47.267901  55.250550  13.174932  8.921404
Gemini 1.5 Flash   0.310760  22.122232  23.598343   1.514955  4.169364
Gemini 1.5 Pro     1.288359  25.767189  21.306487   1.618542  5.412405
Gemini 2.0 Flash   5.703742  20.290043  19.390133   2.499029  4.771462
VideoLLaMA 2      27.981354  17.007640  21.461867  11.161466  2.848634
Unified-IO 2      32.280202  20.238249  52.395442   4.875049  3.418361
PandaGPT           5.198757   7.652467   8.947300   4.506021  4.480124
OLA               10.714748   8.630066  14.294963   7.613622  4.052829

metric
modality                av
CAV-MAE           0.666839
DeepAVFusion      0.067367
Equi-AV           0.977599
AV-Siam           3.923346
Gemini 1.5 Flash  0.090638
Gemini 1.5 Pro    0.239544
Gemini 2.0 Flash  0.627994
VideoLLaMA 2      1.417843
Unified-IO 2      0.874013
PandaGPT          0.938754
OLA               0.712158

In [9]:
print(table_9.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av \\
\midrule
CAV-MAE & 59.05 & 45.57 & 65.08 & 4.71 & 4.84 & 0.67 \\
DeepAVFusion & 40.82 & 27.24 & 53.10 & 4.18 & 3.17 & 0.07 \\
Equi-AV & 46.68 & 24.84 & 50.08 & 6.91 & 5.51 & 0.98 \\
AV-Siam & 56.91 & 47.27 & 55.25 & 13.17 & 8.92 & 3.92 \\
Gemini 1.5 Flash & 0.31 & 22.12 & 23.60 & 1.51 & 4.17 & 0.09 \\
Gemini 1.5 Pro & 1.29 & 25.77 & 21.31 & 1.62 & 5.41 & 0.24 \\
Gemini 2.0 Flash & 5.70 & 20.29 & 19.39 & 2.50 & 4.77 & 0.63 \\
VideoLLaMA 2 & 27.98 & 17.01 & 21.46 & 11.16 & 2.85 & 1.42 \\
Unified-IO 2 & 32.28 & 20.24 & 52.40 & 4.88 & 3.42 & 0.87 \\
PandaGPT & 5.20 & 7.65 & 8.95 & 4.51 & 4.48 & 0.94 \\
OLA & 10.71 & 8.63 & 14.29 & 7.61 & 4.05 & 0.71 \\
\bottomrule
\end{tabular}

# Table 7
**Audio-visual video classification results on VGGSounder for k ∈ {3, 5, 10}.** The table is vertically grouped by k. Within each block, the four models are compared across the three metrics and input modalities

In [11]:
from vggsounder.benchmark import benchmark
import pandas as pd

vggsounder = VGGSounder()
# top 3 table
top_3_table = benchmark(
    models_path="../../supplimentary/models-results",
    display_names = {
        "cav-mae": "CAV-MAE",
        "deepavfusion": "DeepAVFusion",
        "equiav": "Equi-AV",
        "avsiam": "AV-Siam",
    },
    metrics=[
        ("accuracy@3", ["a", "v", "av"]),
        ("f1@3", ["a", "v", "av"]),
        ("hit_rate@3", ["a", "v", "av"]),
    ],
    vggsounder=vggsounder
)

# top 5 table
top_5_table = benchmark(
    models_path="../../supplimentary/models-results",
    display_names = {
        "cav-mae": "CAV-MAE",
        "deepavfusion": "DeepAVFusion",
        "equiav": "Equi-AV",
        "avsiam": "AV-Siam",
    },
    metrics=[
        ("accuracy@5", ["a", "v", "av"]),
        ("f1@5", ["a", "v", "av"]),
        ("hit_rate@5", ["a", "v", "av"]),
    ],
    vggsounder=vggsounder
)

# top 10 table
top_10_table = benchmark(
    models_path="../../supplimentary/models-results",
    display_names = {
        "cav-mae": "CAV-MAE",
        "deepavfusion": "DeepAVFusion",
        "equiav": "Equi-AV",
        "avsiam": "AV-Siam",
    },
    metrics=[
        ("accuracy@10", ["a", "v", "av"]),
        ("f1@10", ["a", "v", "av"]),
        ("hit_rate@10", ["a", "v", "av"]),
    ],
    vggsounder=vggsounder
)

# rename columns 
new_cols = [(col[0].split("@")[0], col[1]) for col in top_10_table.columns.to_list()]
top_3_table.columns = pd.MultiIndex.from_tuples(new_cols)
top_5_table.columns = pd.MultiIndex.from_tuples(new_cols)
top_10_table.columns = pd.MultiIndex.from_tuples(new_cols)

# concat to get the final table
table_7 = pd.concat([top_3_table, top_5_table, top_10_table])
table_7

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

              accuracy                             f1                        \
                     a         v        av          a          v         av
CAV-MAE       0.993890  0.561305  1.085689  39.084762  35.584821  42.916995
DeepAVFusion  0.220919  0.082335  0.683009  28.067097  22.429400  37.360258
Equi-AV       0.545825  0.236801  0.340960  33.504541  22.782880  34.057867
AV-Siam       0.830957  0.771794  0.744729  37.361075  37.047305  40.908114
CAV-MAE       0.040733  0.035082  0.026918  35.150633  30.789676  35.998567
DeepAVFusion  0.000000  0.000000  0.000000  24.905467  19.477004  31.060475
Equi-AV       0.008147  0.008770  0.000000  30.058199  20.441166  28.622252
AV-Siam       0.016293  0.043852  0.017945  33.126498  31.877686  34.670216
CAV-MAE       0.000000  0.000000  0.000000  25.616253  21.658765  24.361493
DeepAVFusion  0.000000  0.000000  0.000000  18.362784  14.226779  21.062797
Equi-AV       0.000000  0.000000  0.000000  22.393718  15.238068  19.836106
AV-Siam       0.000000  0.000000  0.000000  24.148999  22.124138  23.938685

               hit_rate
                      a          v         av
CAV-MAE       81.156823  72.136467  82.548228
DeepAVFusion  65.145722  50.855365  74.747380
Equi-AV       73.816701  48.131907  70.776133
AV-Siam       79.307536  73.206455  79.829520
CAV-MAE       87.046843  78.731801  87.644684
DeepAVFusion  72.240632  58.475894  80.379865
Equi-AV       80.635438  55.665673  77.092867
AV-Siam       84.814664  79.573759  85.527142
CAV-MAE       91.641548  85.265743  92.005384
DeepAVFusion  80.346673  67.871192  85.703593
Equi-AV       87.413442  65.488511  83.768506
AV-Siam       90.085540  85.862129  90.991476

# Table 8 
**Audio-visual video classification results on the subset of VGGSounder that is labelled as containing background music**

In [2]:
from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
vggsounder = VGGSounder(csv_path=csv_path)

# background_music
vggsounder.set_meta_filters(background_music=True)
background_music_ids = [video.video_id for video in vggsounder]

background_music_only_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    subset_ids=background_music_ids,
    dataset_path=csv_path
)
background_music_only_table

  0%|          | 0/11 [00:00<?, ?it/s]

metric             accuracy                               f1             \
modality                  a          v         av          a          v
CAV-MAE           10.798917  19.172932  23.869565  31.033512  31.315056
DeepAVFusion       8.153310   9.482759  20.700494  21.655066  16.431711
Equi-AV            9.106297  10.108605  19.739130  25.326199  17.885940
AV-Siam           10.460393  18.504595  21.347826  29.550361  31.021844
Gemini 1.5 Flash   1.150982  13.909774  14.739130  13.311819  34.589928
Gemini 1.5 Pro     1.895735  20.843776  20.739130  17.401410  46.060449
Gemini 2.0 Flash   1.083277  11.319967  10.434783  11.331916  32.162606
VideoLLaMA 2      11.238998  18.629908  22.695652  36.434847  43.202208
Unified-IO 2       9.106297  13.450292  24.521739  28.903912  29.068656
PandaGPT           1.861882   4.636591   5.782609  12.753553  17.635108
OLA                8.530806   9.774436  19.173913  35.866908  25.470782

metric                                              hit_rate             \
modality                 av     a only     v only          a          v
CAV-MAE           38.614477  17.834631  22.264875  55.958023  44.611529
DeepAVFusion      33.076181  12.642369   8.267717  39.024390  23.362069
Equi-AV           32.152842  14.720059  11.516315  45.666892  25.480368
AV-Siam           34.327431  16.499815  22.648752  53.283683  44.193818
Gemini 1.5 Flash  38.351693  11.489097  22.099448  30.467163  44.277360
Gemini 1.5 Pro    47.941027  13.681262  27.495908  33.649289  62.406015
Gemini 2.0 Flash  32.981340   9.843158  21.839080  18.618822  39.849624
VideoLLaMA 2      46.826667  23.934567  33.410673  53.859174  43.692565
Unified-IO 2      44.713100  20.731143  22.969188  42.552471  28.822055
PandaGPT          18.103262   8.655570  16.091954  14.962762  15.497076
OLA               43.604549  29.257095  17.174515  44.346649  23.475355

metric                              mu
modality                 av          a         v        av
CAV-MAE           54.043478   5.931918  5.561173  0.876306
DeepAVFusion      46.205658   3.537981  3.121748  0.242803
Equi-AV           45.000000   6.943040  5.190428  1.011122
AV-Siam           48.043478  13.919784  7.718234  3.471520
Gemini 1.5 Flash  53.478261  15.200539  3.538928  1.112235
Gemini 1.5 Pro    67.521739   6.100438  3.673745  0.741490
Gemini 2.0 Flash  43.130435   3.640040  3.977081  0.842602
VideoLLaMA 2      48.391304  20.829120  4.785979  2.898551
Unified-IO 2      52.260870   9.571958  5.291540  1.516684
PandaGPT          15.173913   8.628244  5.999326  2.527806
OLA               44.826087  14.459050  6.302663  1.954837

In [3]:
print(background_music_only_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 10.80 & 19.17 & 23.87 & 31.03 & 31.32 & 38.61 & 17.83 & 22.26 & 55.96 & 44.61 & 54.04 & 5.93 & 5.56 & 0.88 \\
DeepAVFusion & 8.15 & 9.48 & 20.70 & 21.66 & 16.43 & 33.08 & 12.64 & 8.27 & 39.02 & 23.36 & 46.21 & 3.54 & 3.12 & 0.24 \\
Equi-AV & 9.11 & 10.11 & 19.74 & 25.33 & 17.89 & 32.15 & 14.72 & 11.52 & 45.67 & 25.48 & 45.00 & 6.94 & 5.19 & 1.01 \\
AV-Siam & 10.46 & 18.50 & 21.35 & 29.55 & 31.02 & 34.33 & 16.50 & 22.65 & 53.28 & 44.19 & 48.04 & 13.92 & 7.72 & 3.47 \\
Gemini 1.5 Flash & 1.15 & 13.91 & 14.74 & 13.31 & 34.59 & 38.35 & 11.49 & 22.10 & 30.47 & 44.28 & 53.48 & 15.20 & 3.54 & 1.11 \\
Gemini 1.5 Pro & 1.90 & 20.84 & 20.74 & 17.40 & 46.06 & 47.94 & 13.68 & 27.50 & 33.65 & 62.41 & 67.52 & 6.10 & 3.67 & 0.74 \\
Gemini 2.0 Flash & 1.08 & 11.32 & 10.43 & 11.33 & 32.16 & 32.98 & 9.84 & 21.84 & 18.62 & 39.85 & 43.13 & 3.64 & 3.98 & 0.84 \\
VideoLLaMA 2 & 11.24 & 18.63 & 22.70 & 36.43 & 43.20 & 46.83 & 23.93 & 33.41 & 53.86 & 43.69 & 48.39 & 20.83 & 4.79 & 2.90 \\
Unified-IO 2 & 9.11 & 13.45 & 24.52 & 28.90 & 29.07 & 44.71 & 20.73 & 22.97 & 42.55 & 28.82 & 52.26 & 9.57 & 5.29 & 1.52 \\
PandaGPT & 1.86 & 4.64 & 5.78 & 12.75 & 17.64 & 18.10 & 8.66 & 16.09 & 14.96 & 15.50 & 15.17 & 8.63 & 6.00 & 2.53 \\
OLA & 8.53 & 9.77 & 19.17 & 35.87 & 25.47 & 43.60 & 29.26 & 17.17 & 44.35 & 23.48 & 44.83 & 14.46 & 6.30 & 1.95 \\
\bottomrule
\end{tabular}

# Table 9 
**Audio-visual video classification results on the subset of VGGSounder that is labelled as not containing background music**

In [4]:
from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
vggsounder = VGGSounder(csv_path=csv_path)


# no background music
vggsounder.set_meta_filters(background_music=False)
no_background_music_ids = [video.video_id for video in vggsounder]

no_background_music_only_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    subset_ids=no_background_music_ids,
    dataset_path=csv_path
)
no_background_music_only_table

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

metric             accuracy                               f1             \
modality                  a          v         av          a          v
CAV-MAE           13.189409  19.233468  24.486317  34.467682  34.910904
DeepAVFusion      10.187781  11.096880  21.528817  25.305931  21.293116
Equi-AV           11.600815  10.515699  20.000000  29.392410  20.420558
AV-Siam           12.790224  19.750921  22.826380  33.295772  35.409385
Gemini 1.5 Flash   1.784114  14.444834  16.437865  14.485788  36.982343
Gemini 1.5 Pro     3.054990  20.855990  22.530283  19.262950  49.733103
Gemini 2.0 Flash   1.849287  12.541659  12.687304  11.798212  34.081168
VideoLLaMA 2      12.863544  19.847395  24.468371  38.866072  47.822374
Unified-IO 2      11.942974  11.559376  25.607896  35.309780  27.917454
PandaGPT           3.193483   4.192247   5.464334  18.731493  18.560851
OLA               14.109980   8.691458  18.187528  47.704685  24.845718

metric                                              hit_rate             \
modality                 av     a only     v only          a          v
CAV-MAE           42.619629  13.943105  19.004975  62.297352  53.437993
DeepAVFusion      37.348238  10.366826  10.548303  45.772793  32.613668
Equi-AV           34.693999  12.552622  10.646766  53.124236  31.257674
AV-Siam           39.425541  12.897053  18.208955  60.179226  54.201017
Gemini 1.5 Flash  42.524935  15.605109  21.605550  32.733198  47.360112
Gemini 1.5 Pro    53.740119  17.732038  22.898799  35.030550  69.233468
Gemini 2.0 Flash  36.452372   6.185984  18.896834  18.509165  43.825645
VideoLLaMA 2      52.351387  20.340482  28.083700  58.908350  52.017190
Unified-IO 2      48.892540  21.378038  16.534867  54.386965  31.047185
PandaGPT          20.848513  16.816454  14.401176  21.075356  17.014559
OLA               46.477763  40.438831  13.445378  59.054990  24.565866

metric                              mu
modality                 av          a         v        av
CAV-MAE           64.172275   3.960556  6.005496  0.905270
DeepAVFusion      56.268713   4.098153  3.727127  0.193946
Equi-AV           52.238672   7.953443  6.910766  1.584222
AV-Siam           59.362943  10.297446  8.688975  3.750404
Gemini 1.5 Flash  59.102737  14.363078  4.097963  1.471064
Gemini 1.5 Pro    75.423957   3.071452  4.227287  0.711284
Gemini 2.0 Flash  47.716465   2.578403  5.253799  1.034594
VideoLLaMA 2      59.802602  14.338830  5.431620  3.192693
Unified-IO 2      65.105428  10.200453  4.671840  1.915616
PandaGPT          18.824585  10.063046  6.627869  3.216941
OLA               51.511889  17.070805  6.320724  2.901714

In [5]:
print(no_background_music_only_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 13.19 & 19.23 & 24.49 & 34.47 & 34.91 & 42.62 & 13.94 & 19.00 & 62.30 & 53.44 & 64.17 & 3.96 & 6.01 & 0.91 \\
DeepAVFusion & 10.19 & 11.10 & 21.53 & 25.31 & 21.29 & 37.35 & 10.37 & 10.55 & 45.77 & 32.61 & 56.27 & 4.10 & 3.73 & 0.19 \\
Equi-AV & 11.60 & 10.52 & 20.00 & 29.39 & 20.42 & 34.69 & 12.55 & 10.65 & 53.12 & 31.26 & 52.24 & 7.95 & 6.91 & 1.58 \\
AV-Siam & 12.79 & 19.75 & 22.83 & 33.30 & 35.41 & 39.43 & 12.90 & 18.21 & 60.18 & 54.20 & 59.36 & 10.30 & 8.69 & 3.75 \\
Gemini 1.5 Flash & 1.78 & 14.44 & 16.44 & 14.49 & 36.98 & 42.52 & 15.61 & 21.61 & 32.73 & 47.36 & 59.10 & 14.36 & 4.10 & 1.47 \\
Gemini 1.5 Pro & 3.05 & 20.86 & 22.53 & 19.26 & 49.73 & 53.74 & 17.73 & 22.90 & 35.03 & 69.23 & 75.42 & 3.07 & 4.23 & 0.71 \\
Gemini 2.0 Flash & 1.85 & 12.54 & 12.69 & 11.80 & 34.08 & 36.45 & 6.19 & 18.90 & 18.51 & 43.83 & 47.72 & 2.58 & 5.25 & 1.03 \\
VideoLLaMA 2 & 12.86 & 19.85 & 24.47 & 38.87 & 47.82 & 52.35 & 20.34 & 28.08 & 58.91 & 52.02 & 59.80 & 14.34 & 5.43 & 3.19 \\
Unified-IO 2 & 11.94 & 11.56 & 25.61 & 35.31 & 27.92 & 48.89 & 21.38 & 16.53 & 54.39 & 31.05 & 65.11 & 10.20 & 4.67 & 1.92 \\
PandaGPT & 3.19 & 4.19 & 5.46 & 18.73 & 18.56 & 20.85 & 16.82 & 14.40 & 21.08 & 17.01 & 18.82 & 10.06 & 6.63 & 3.22 \\
OLA & 14.11 & 8.69 & 18.19 & 47.70 & 24.85 & 46.48 & 40.44 & 13.45 & 59.05 & 24.57 & 51.51 & 17.07 & 6.32 & 2.90 \\
\bottomrule
\end{tabular}

# Table 10 
**Audio-visual video classification results on the subset of VGGSounder that is labelled as containing static images**

In [8]:
from vggsounder.benchmark import benchmark, compute_all_results
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}

# static image
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(static_image=True)
static_image_ids = [video.video_id for video in vggsounder]

static_image_results = compute_all_results(
    models_path=models_path,
    models_filter=display_names.keys(),
    subset_ids=static_image_ids,
    dataset_path=csv_path
)

static_image_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    subset_ids=static_image_ids,
    dataset_path=csv_path
)
static_image_table

  0%|          | 0/11 [00:00<?, ?it/s]

  0%|          | 0/11 [00:00<?, ?it/s]

metric             accuracy                               f1             \
modality                  a          v         av          a          v
CAV-MAE           22.132616  19.480519  27.416520  38.241881  27.209154
DeepAVFusion      15.981308  10.958904  23.204420  28.646441  15.796519
Equi-AV           18.996416  10.389610  22.495606  32.586786  14.240305
AV-Siam           22.043011  19.805195  24.253076  37.458007  28.099174
Gemini 1.5 Flash   1.433692  13.474026  15.641476   9.345093  29.512894
Gemini 1.5 Pro     2.329749  22.077922  23.374341  14.315888  42.498469
Gemini 2.0 Flash   3.853047  10.876623  13.884007  13.538111  26.912568
VideoLLaMA 2      18.996416  18.181818  23.725835  42.358219  37.899918
Unified-IO 2      17.921147   9.577922  28.471002  35.871743  22.121487
PandaGPT           3.315412   4.870130   5.272408  14.145234  13.714286
OLA               14.874552   8.603896  18.277680  37.796834  19.723502

metric                                              hit_rate             \
modality                 av     a only     v only          a          v
CAV-MAE           37.622378  35.177539  15.028902  61.200717  34.740260
DeepAVFusion      31.501832  26.426426   6.329114  45.887850  20.205479
Equi-AV           31.328671  30.140380   9.248555  52.150538  18.181818
AV-Siam           34.265734  33.608588  13.872832  59.946237  35.876623
Gemini 1.5 Flash  33.266533   8.146965  18.633540  20.250896  30.194805
Gemini 1.5 Pro    44.885307  12.521266  24.444444  24.193548  51.298701
Gemini 2.0 Flash  31.636864  12.819439  13.750000  19.534050  29.870130
VideoLLaMA 2      43.220339  39.409805  27.536232  56.451613  32.305195
Unified-IO 2      45.950413  33.450527  15.929204  47.491039  18.344156
PandaGPT          15.320911  12.751292  11.009174  14.784946  11.363636
OLA               38.884193  33.529412  10.526316  42.293907  15.584416

metric                              mu
modality                 av          a         v        av
CAV-MAE           47.275923   5.540897  4.397537  0.175901
DeepAVFusion      39.594843   4.696133  3.038674  0.184162
Equi-AV           39.367311   7.651715  3.957784  0.703606
AV-Siam           43.057996  15.479332  6.332454  3.078276
Gemini 1.5 Flash  40.597540  10.817942  3.869833  0.439754
Gemini 1.5 Pro    57.469244   4.573439  4.749340  0.527704
Gemini 2.0 Flash  38.312830   2.902375  3.342128  0.791557
VideoLLaMA 2      40.597540  22.163588  4.133685  2.638522
Unified-IO 2      47.803163   8.443272  2.726473  0.967458
PandaGPT          11.775044   9.850484  5.364996  2.286719
OLA               34.973638  17.062445  3.781882  1.143360

In [10]:
print(static_image_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 22.13 & 19.48 & 27.42 & 38.24 & 27.21 & 37.62 & 35.18 & 15.03 & 61.20 & 34.74 & 47.28 & 5.54 & 4.40 & 0.18 \\
DeepAVFusion & 15.98 & 10.96 & 23.20 & 28.65 & 15.80 & 31.50 & 26.43 & 6.33 & 45.89 & 20.21 & 39.59 & 4.70 & 3.04 & 0.18 \\
Equi-AV & 19.00 & 10.39 & 22.50 & 32.59 & 14.24 & 31.33 & 30.14 & 9.25 & 52.15 & 18.18 & 39.37 & 7.65 & 3.96 & 0.70 \\
AV-Siam & 22.04 & 19.81 & 24.25 & 37.46 & 28.10 & 34.27 & 33.61 & 13.87 & 59.95 & 35.88 & 43.06 & 15.48 & 6.33 & 3.08 \\
Gemini 1.5 Flash & 1.43 & 13.47 & 15.64 & 9.35 & 29.51 & 33.27 & 8.15 & 18.63 & 20.25 & 30.19 & 40.60 & 10.82 & 3.87 & 0.44 \\
Gemini 1.5 Pro & 2.33 & 22.08 & 23.37 & 14.32 & 42.50 & 44.89 & 12.52 & 24.44 & 24.19 & 51.30 & 57.47 & 4.57 & 4.75 & 0.53 \\
Gemini 2.0 Flash & 3.85 & 10.88 & 13.88 & 13.54 & 26.91 & 31.64 & 12.82 & 13.75 & 19.53 & 29.87 & 38.31 & 2.90 & 3.34 & 0.79 \\
VideoLLaMA 2 & 19.00 & 18.18 & 23.73 & 42.36 & 37.90 & 43.22 & 39.41 & 27.54 & 56.45 & 32.31 & 40.60 & 22.16 & 4.13 & 2.64 \\
Unified-IO 2 & 17.92 & 9.58 & 28.47 & 35.87 & 22.12 & 45.95 & 33.45 & 15.93 & 47.49 & 18.34 & 47.80 & 8.44 & 2.73 & 0.97 \\
PandaGPT & 3.32 & 4.87 & 5.27 & 14.15 & 13.71 & 15.32 & 12.75 & 11.01 & 14.78 & 11.36 & 11.78 & 9.85 & 5.36 & 2.29 \\
OLA & 14.87 & 8.60 & 18.28 & 37.80 & 19.72 & 38.88 & 33.53 & 10.53 & 42.29 & 15.58 & 34.97 & 17.06 & 3.78 & 1.14 \\
\bottomrule
\end{tabular}

# Table 11 
**Audio-visual video classification results on the subset of VGGSounder that is labelled as not containing static images**

In [11]:
from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}

# no static image
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(static_image=False)
no_static_image_ids = [video.video_id for video in vggsounder]

no_static_image_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    subset_ids=no_static_image_ids,
    dataset_path=csv_path
)
no_static_image_table

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

metric             accuracy                               f1             \
modality                  a          v         av          a          v
CAV-MAE           11.981861  19.210926  24.246660  33.494646  34.601783
DeepAVFusion       9.300612  10.807610  21.306175  24.311491  20.674821
Equi-AV           10.493871  10.447648  19.843119  28.328766  20.232106
AV-Siam           11.570892  19.522003  22.499223  32.231357  34.950441
Gemini 1.5 Flash   1.679303  14.393020  16.169618  14.623026  36.826641
Gemini 1.5 Pro     2.869695  20.796662  22.173035  19.215737  49.362859
Gemini 2.0 Flash   1.530504  12.397572  12.232060  11.575588  34.021199
VideoLLaMA 2      12.038546  19.704097  24.184529  38.133944  47.416699
Unified-IO 2      10.876497  11.995448  25.287356  33.990552  28.309637
PandaGPT           2.905123   4.241275   5.529668  17.827909  18.578475
OLA               12.881740   8.892261  18.359739  46.032693  25.124797

metric                                              hit_rate             \
modality                 av     a only     v only          a          v
CAV-MAE           42.136375  12.310992  20.016964  61.057181  52.708649
DeepAVFusion      36.846366   8.951904  10.331126  44.336355  31.491277
Equi-AV           34.394607  10.895442  10.941476  51.640332  30.819423
AV-Siam           38.765880  11.249330  19.508058  58.754340  53.239757
Gemini 1.5 Flash  42.134114  15.429769  21.916667  33.245943  47.602428
Gemini 1.5 Pro    53.069434  17.236461  23.814694  35.598384  68.831563
Gemini 2.0 Flash  36.026278   6.433333  19.913793  18.451073  43.755690
VideoLLaMA 2      51.785117  18.890406  29.208156  58.045773  51.426404
Unified-IO 2      48.328635  19.628301  17.981651  52.455183  31.236722
PandaGPT          20.596095  15.011648  15.000000  20.293347  17.003035
OLA               46.272650  38.296256  14.447761  57.301779  24.787557

metric                              mu
modality                 av          a         v        av
CAV-MAE           63.109661   4.245881  6.041403  0.957612
DeepAVFusion      55.189137   3.932337  3.654071  0.205038
Equi-AV           51.514445   7.766512  6.787776  1.534995
AV-Siam           58.061510  10.639347  8.674835  3.745951
Gemini 1.5 Flash  58.915812  14.821856  3.999437  1.478665
Gemini 1.5 Pro    74.805840   3.584002  4.069849  0.732291
Gemini 2.0 Flash  47.312830   2.774257  5.140121  1.013942
VideoLLaMA 2      58.612923  15.068300  5.400648  3.175609
Unified-IO 2      63.575645  10.209830  4.957048  1.908182
PandaGPT          18.484001   9.780313  6.597662  3.147444
OLA               51.048462  16.525841  6.520208  2.844670

In [12]:
print(no_static_image_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 11.98 & 19.21 & 24.25 & 33.49 & 34.60 & 42.14 & 12.31 & 20.02 & 61.06 & 52.71 & 63.11 & 4.25 & 6.04 & 0.96 \\
DeepAVFusion & 9.30 & 10.81 & 21.31 & 24.31 & 20.67 & 36.85 & 8.95 & 10.33 & 44.34 & 31.49 & 55.19 & 3.93 & 3.65 & 0.21 \\
Equi-AV & 10.49 & 10.45 & 19.84 & 28.33 & 20.23 & 34.39 & 10.90 & 10.94 & 51.64 & 30.82 & 51.51 & 7.77 & 6.79 & 1.53 \\
AV-Siam & 11.57 & 19.52 & 22.50 & 32.23 & 34.95 & 38.77 & 11.25 & 19.51 & 58.75 & 53.24 & 58.06 & 10.64 & 8.67 & 3.75 \\
Gemini 1.5 Flash & 1.68 & 14.39 & 16.17 & 14.62 & 36.83 & 42.13 & 15.43 & 21.92 & 33.25 & 47.60 & 58.92 & 14.82 & 4.00 & 1.48 \\
Gemini 1.5 Pro & 2.87 & 20.80 & 22.17 & 19.22 & 49.36 & 53.07 & 17.24 & 23.81 & 35.60 & 68.83 & 74.81 & 3.58 & 4.07 & 0.73 \\
Gemini 2.0 Flash & 1.53 & 12.40 & 12.23 & 11.58 & 34.02 & 36.03 & 6.43 & 19.91 & 18.45 & 43.76 & 47.31 & 2.77 & 5.14 & 1.01 \\
VideoLLaMA 2 & 12.04 & 19.70 & 24.18 & 38.13 & 47.42 & 51.79 & 18.89 & 29.21 & 58.05 & 51.43 & 58.61 & 15.07 & 5.40 & 3.18 \\
Unified-IO 2 & 10.88 & 12.00 & 25.29 & 33.99 & 28.31 & 48.33 & 19.63 & 17.98 & 52.46 & 31.24 & 63.58 & 10.21 & 4.96 & 1.91 \\
PandaGPT & 2.91 & 4.24 & 5.53 & 17.83 & 18.58 & 20.60 & 15.01 & 15.00 & 20.29 & 17.00 & 18.48 & 9.78 & 6.60 & 3.15 \\
OLA & 12.88 & 8.89 & 18.36 & 46.03 & 25.12 & 46.27 & 38.30 & 14.45 & 57.30 & 24.79 & 51.05 & 16.53 & 6.52 & 2.84 \\
\bottomrule
\end{tabular}

# Table 12
**Audio-visual video classification results on the subset of VGGSounder that is labelled as containing voice over narrations**

In [13]:
from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
# voice over
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(voice_over=True)
voice_over_ids = [video.video_id for video in vggsounder]


voice_over_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    subset_ids=voice_over_ids,
    dataset_path=csv_path
)
voice_over_table

  0%|          | 0/11 [00:00<?, ?it/s]

metric             accuracy                               f1             \
modality                  a          v         av          a          v
CAV-MAE            2.783505  14.343551  17.378410  26.734123  28.356242
DeepAVFusion       2.018056   9.410363  15.332926  16.787821  17.780360
Equi-AV            3.505155   7.750145  14.531435  22.447078  15.439654
AV-Siam            2.731959  13.938693  15.658363  25.695646  28.506873
Gemini 1.5 Flash   5.257732   9.427415  10.854093  29.430582  30.610255
Gemini 1.5 Pro     7.731959  17.698091  16.073547  34.584156  46.218066
Gemini 2.0 Flash   0.721649   7.403123   8.362989  11.873425  27.473394
VideoLLaMA 2       6.340206  16.078658  19.395018  34.976387  42.756259
Unified-IO 2       4.690722   9.080393  18.149466  29.806668  24.800194
PandaGPT           3.659794   4.279931   4.863582  20.963082  18.578152
OLA               15.463918   7.056102  16.132859  54.144368  23.476190

metric                                              hit_rate             \
modality                 av     a only     v only          a          v
CAV-MAE           35.374682  11.188811  25.503356  51.752577  43.551186
DeepAVFusion      29.134809   6.507984  13.986014  32.501328  27.337701
Equi-AV           28.135394   9.615385  10.738255  43.453608  23.713129
AV-Siam           31.109372   9.557110  26.845638  49.742268  43.782533
Gemini 1.5 Flash  34.008393  27.552537  23.606557  63.711340  40.023135
Gemini 1.5 Pro    50.839695  29.259590  27.762040  68.298969  65.702718
Gemini 2.0 Flash  29.847284   6.104468  21.621622  19.948454  36.379410
VideoLLaMA 2      47.722435  21.740603  36.144578  54.432990  47.599769
Unified-IO 2      40.941704  23.166844  21.649485  48.608247  27.125506
PandaGPT          18.922403  19.073569  17.733990  26.752577  17.466744
OLA               48.531388  47.313596  16.080402  76.082474  24.638519

metric                              mu
modality                 av          a         v        av
CAV-MAE           53.618031   5.341551  6.471495  0.821777
DeepAVFusion      44.227245   3.121693  3.439153  0.158730
Equi-AV           42.645314   9.090909  5.649718  1.181305
AV-Siam           47.153025  11.967129  8.577298  3.697997
Gemini 1.5 Flash  48.279953  32.717001  4.365691  2.876220
Gemini 1.5 Pro    75.504152   6.625578  3.133025  1.386749
Gemini 2.0 Flash  40.569395   3.030303  5.392912  1.438110
VideoLLaMA 2      54.685647  17.051875  5.752440  3.389831
Unified-IO 2      53.440095  14.124294  4.879301  2.259887
PandaGPT          18.030842  13.867488  7.755521  4.365691
OLA               57.532622  17.514124  4.673857  3.389831

In [14]:
print(voice_over_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 2.78 & 14.34 & 17.38 & 26.73 & 28.36 & 35.37 & 11.19 & 25.50 & 51.75 & 43.55 & 53.62 & 5.34 & 6.47 & 0.82 \\
DeepAVFusion & 2.02 & 9.41 & 15.33 & 16.79 & 17.78 & 29.13 & 6.51 & 13.99 & 32.50 & 27.34 & 44.23 & 3.12 & 3.44 & 0.16 \\
Equi-AV & 3.51 & 7.75 & 14.53 & 22.45 & 15.44 & 28.14 & 9.62 & 10.74 & 43.45 & 23.71 & 42.65 & 9.09 & 5.65 & 1.18 \\
AV-Siam & 2.73 & 13.94 & 15.66 & 25.70 & 28.51 & 31.11 & 9.56 & 26.85 & 49.74 & 43.78 & 47.15 & 11.97 & 8.58 & 3.70 \\
Gemini 1.5 Flash & 5.26 & 9.43 & 10.85 & 29.43 & 30.61 & 34.01 & 27.55 & 23.61 & 63.71 & 40.02 & 48.28 & 32.72 & 4.37 & 2.88 \\
Gemini 1.5 Pro & 7.73 & 17.70 & 16.07 & 34.58 & 46.22 & 50.84 & 29.26 & 27.76 & 68.30 & 65.70 & 75.50 & 6.63 & 3.13 & 1.39 \\
Gemini 2.0 Flash & 0.72 & 7.40 & 8.36 & 11.87 & 27.47 & 29.85 & 6.10 & 21.62 & 19.95 & 36.38 & 40.57 & 3.03 & 5.39 & 1.44 \\
VideoLLaMA 2 & 6.34 & 16.08 & 19.40 & 34.98 & 42.76 & 47.72 & 21.74 & 36.14 & 54.43 & 47.60 & 54.69 & 17.05 & 5.75 & 3.39 \\
Unified-IO 2 & 4.69 & 9.08 & 18.15 & 29.81 & 24.80 & 40.94 & 23.17 & 21.65 & 48.61 & 27.13 & 53.44 & 14.12 & 4.88 & 2.26 \\
PandaGPT & 3.66 & 4.28 & 4.86 & 20.96 & 18.58 & 18.92 & 19.07 & 17.73 & 26.75 & 17.47 & 18.03 & 13.87 & 7.76 & 4.37 \\
OLA & 15.46 & 7.06 & 16.13 & 54.14 & 23.48 & 48.53 & 47.31 & 16.08 & 76.08 & 24.64 & 57.53 & 17.51 & 4.67 & 3.39 \\
\bottomrule
\end{tabular}

# Table 13 
**Audio-visual video classification results on the subset of VGGSounder that is labelled as not containing voice over narrations**

In [15]:

from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
# no voice over
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(voice_over=False)
no_voice_over_ids = [video.video_id for video in vggsounder]


no_voice_over_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    subset_ids=no_voice_over_ids,
    dataset_path=csv_path
)
no_voice_over_table

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

metric             accuracy                               f1             \
modality                  a          v         av          a          v
CAV-MAE           14.177139  19.922102  25.384812  34.920234  35.193322
DeepAVFusion      10.936030  11.017974  22.264586  25.839397  20.894069
Equi-AV           12.228159  10.831193  20.733056  29.578651  20.672232
AV-Siam           13.740688  20.336455  23.564929  33.657448  35.594244
Gemini 1.5 Flash   1.136278  15.057595  16.906200  12.179131  37.427257
Gemini 1.5 Pro     2.114531  21.306041  23.105706  16.420321  49.550972
Gemini 2.0 Flash   1.843630  13.035552  12.866740  11.678204  34.664861
VideoLLaMA 2      13.454737  20.145852  24.849052  38.945614  47.727550
Unified-IO 2      12.371134  12.289716  26.464835  34.788264  28.577418
PandaGPT           2.829408   4.267838   5.612722  17.046607  18.390889
OLA               12.672135   9.140631  18.675057  44.053084  25.162338

metric                                              hit_rate             \
modality                 av     a only     v only          a          v
CAV-MAE           42.941901  15.668934  18.898343  62.427572  53.103505
DeepAVFusion      37.773859  11.825616   9.546093  46.213547  31.524369
Equi-AV           35.185875  13.786848  10.837438  52.878320  31.192508
AV-Siam           39.703058  14.648526  18.092253  60.170065  53.708461
Gemini 1.5 Flash  42.934296  12.376649  21.453901  27.707126  47.799785
Gemini 1.5 Pro    53.103019  14.289442  23.320463  29.866807  68.384851
Gemini 2.0 Flash  36.733678   7.379859  19.230769  18.323425  44.103754
VideoLLaMA 2      52.062844  21.163674  28.228228  58.439311  50.998591
Unified-IO 2      49.282813  20.837068  17.374517  52.599895  31.167647
PandaGPT          20.649237  13.898358  14.342629  18.887802  16.648711
OLA               45.636460  35.762692  13.962264  53.299722  24.339107

metric                              mu
modality                 av          a         v        av
CAV-MAE           63.704397   4.196535  5.839307  0.910992
DeepAVFusion      56.029438   4.116091  3.633676  0.210084
Equi-AV           52.198316   7.564217  6.712963  1.515830
AV-Siam           58.899566  10.857228  8.490143  3.696237
Gemini 1.5 Flash  59.554384  11.880227  3.935185  1.187276
Gemini 1.5 Pro    73.866825   3.225806  4.263740  0.619773
Gemini 2.0 Flash  47.844204   2.747909  4.950717  0.933393
VideoLLaMA 2      58.304278  15.382318  5.241935  3.098865
Unified-IO 2      64.265669   9.490741  4.778973  1.777180
PandaGPT          18.224339   9.192055  6.324671  2.897252
OLA               49.340930  16.427718  6.556153  2.620968

In [16]:
print(no_voice_over_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 14.18 & 19.92 & 25.38 & 34.92 & 35.19 & 42.94 & 15.67 & 18.90 & 62.43 & 53.10 & 63.70 & 4.20 & 5.84 & 0.91 \\
DeepAVFusion & 10.94 & 11.02 & 22.26 & 25.84 & 20.89 & 37.77 & 11.83 & 9.55 & 46.21 & 31.52 & 56.03 & 4.12 & 3.63 & 0.21 \\
Equi-AV & 12.23 & 10.83 & 20.73 & 29.58 & 20.67 & 35.19 & 13.79 & 10.84 & 52.88 & 31.19 & 52.20 & 7.56 & 6.71 & 1.52 \\
AV-Siam & 13.74 & 20.34 & 23.56 & 33.66 & 35.59 & 39.70 & 14.65 & 18.09 & 60.17 & 53.71 & 58.90 & 10.86 & 8.49 & 3.70 \\
Gemini 1.5 Flash & 1.14 & 15.06 & 16.91 & 12.18 & 37.43 & 42.93 & 12.38 & 21.45 & 27.71 & 47.80 & 59.55 & 11.88 & 3.94 & 1.19 \\
Gemini 1.5 Pro & 2.11 & 21.31 & 23.11 & 16.42 & 49.55 & 53.10 & 14.29 & 23.32 & 29.87 & 68.38 & 73.87 & 3.23 & 4.26 & 0.62 \\
Gemini 2.0 Flash & 1.84 & 13.04 & 12.87 & 11.68 & 34.66 & 36.73 & 7.38 & 19.23 & 18.32 & 44.10 & 47.84 & 2.75 & 4.95 & 0.93 \\
VideoLLaMA 2 & 13.45 & 20.15 & 24.85 & 38.95 & 47.73 & 52.06 & 21.16 & 28.23 & 58.44 & 51.00 & 58.30 & 15.38 & 5.24 & 3.10 \\
Unified-IO 2 & 12.37 & 12.29 & 26.46 & 34.79 & 28.58 & 49.28 & 20.84 & 17.37 & 52.60 & 31.17 & 64.27 & 9.49 & 4.78 & 1.78 \\
PandaGPT & 2.83 & 4.27 & 5.61 & 17.05 & 18.39 & 20.65 & 13.90 & 14.34 & 18.89 & 16.65 & 18.22 & 9.19 & 6.32 & 2.90 \\
OLA & 12.67 & 9.14 & 18.68 & 44.05 & 25.16 & 45.64 & 35.76 & 13.96 & 53.30 & 24.34 & 49.34 & 16.43 & 6.56 & 2.62 \\
\bottomrule
\end{tabular}

# Table 14
**Audio-visual video classification results on the subset of VGGSounder that is labelled as not containing background music, static images, or voice over narrations**

In [17]:

from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "cav-mae": "CAV-MAE",
    "deepavfusion": "DeepAVFusion",
    "equiav": "Equi-AV",
    "avsiam": "AV-Siam",
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}

# neither
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(
    static_image=False, 
    voice_over=False, 
    background_music=False
)
neither_ids = [video.video_id for video in vggsounder]

neither_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av", "a only", "v only"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    subset_ids=neither_ids,
    dataset_path=csv_path
)
neither_table

  0%|          | 0/11 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

metric             accuracy                               f1             \
modality                  a          v         av          a          v
CAV-MAE           13.509615  19.526210  24.899640  34.796956  35.591719
DeepAVFusion      10.556391  11.036367  21.844139  25.857622  21.497213
Equi-AV           11.750000  10.725806  20.185280  29.570493  20.971817
AV-Siam           13.019231  20.080645  23.211529  33.583480  36.031366
Gemini 1.5 Flash   1.269231  14.929435  16.901698  12.859051  37.674233
Gemini 1.5 Pro     2.346154  20.856855  22.974781  17.258326  50.008842
Gemini 2.0 Flash   1.846154  13.014113  12.928461  11.733728  34.828354
VideoLLaMA 2      13.019231  20.080645  24.940813  38.867858  48.363374
Unified-IO 2      11.942308  11.764113  25.959856  35.177339  28.251400
PandaGPT           3.000000   4.092742   5.434894  18.209753  18.568262
OLA               13.384615   8.860887  18.239835  46.344695  25.073106

metric                                              hit_rate             \
modality                 av     a only     v only          a          v
CAV-MAE           43.214505  11.714798  18.992472  62.865385  54.677419
DeepAVFusion      38.012008   8.982849  10.271903  46.736842  33.035527
Equi-AV           35.171427  10.670582  10.770122  53.423077  32.217742
AV-Siam           39.990457  10.817425  17.602779  60.673077  55.352823
Gemini 1.5 Flash  43.458371  14.047582  21.547278  29.317308  48.578629
Gemini 1.5 Pro    53.887217  15.689401  22.266600  31.432692  69.778226
Gemini 2.0 Flash  37.088984   5.885363  18.928571  18.384615  44.858871
VideoLLaMA 2      52.840744  17.781973  27.520609  59.105769  52.651210
Unified-IO 2      49.419084  18.841439  16.013344  54.067308  31.622984
PandaGPT          21.082774  15.995575  14.675768  20.336538  17.056452
OLA               46.102288  38.240604  13.128039  56.923077  24.778226

metric                              mu
modality                 av          a         v        av
CAV-MAE           65.259907   3.845787  6.145625  0.954290
DeepAVFusion      57.428081   4.208118  3.780342  0.198965
Equi-AV           53.113742   7.739288  7.119000  1.622292
AV-Siam           60.391148  10.000954  8.779464  3.759901
Gemini 1.5 Flash  60.699949  12.224449  4.008016  1.288291
Gemini 1.5 Pro    75.440041   2.824697  4.275217  0.648917
Gemini 2.0 Flash  48.564076   2.586125  5.248592  0.982918
VideoLLaMA 2      60.422028  13.770398  5.286764  3.101441
Unified-IO 2      66.073083   9.657410  4.800076  1.879950
PandaGPT          18.980957   9.409295  6.508255  3.053727
OLA               50.880082  16.919553  6.708655  2.910583

In [18]:
print(neither_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{5}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a only & v only & a & v & av & a & v & av \\
\midrule
CAV-MAE & 13.51 & 19.53 & 24.90 & 34.80 & 35.59 & 43.21 & 11.71 & 18.99 & 62.87 & 54.68 & 65.26 & 3.85 & 6.15 & 0.95 \\
DeepAVFusion & 10.56 & 11.04 & 21.84 & 25.86 & 21.50 & 38.01 & 8.98 & 10.27 & 46.74 & 33.04 & 57.43 & 4.21 & 3.78 & 0.20 \\
Equi-AV & 11.75 & 10.73 & 20.19 & 29.57 & 20.97 & 35.17 & 10.67 & 10.77 & 53.42 & 32.22 & 53.11 & 7.74 & 7.12 & 1.62 \\
AV-Siam & 13.02 & 20.08 & 23.21 & 33.58 & 36.03 & 39.99 & 10.82 & 17.60 & 60.67 & 55.35 & 60.39 & 10.00 & 8.78 & 3.76 \\
Gemini 1.5 Flash & 1.27 & 14.93 & 16.90 & 12.86 & 37.67 & 43.46 & 14.05 & 21.55 & 29.32 & 48.58 & 60.70 & 12.22 & 4.01 & 1.29 \\
Gemini 1.5 Pro & 2.35 & 20.86 & 22.97 & 17.26 & 50.01 & 53.89 & 15.69 & 22.27 & 31.43 & 69.78 & 75.44 & 2.82 & 4.28 & 0.65 \\
Gemini 2.0 Flash & 1.85 & 13.01 & 12.93 & 11.73 & 34.83 & 37.09 & 5.89 & 18.93 & 18.38 & 44.86 & 48.56 & 2.59 & 5.25 & 0.98 \\
VideoLLaMA 2 & 13.02 & 20.08 & 24.94 & 38.87 & 48.36 & 52.84 & 17.78 & 27.52 & 59.11 & 52.65 & 60.42 & 13.77 & 5.29 & 3.10 \\
Unified-IO 2 & 11.94 & 11.76 & 25.96 & 35.18 & 28.25 & 49.42 & 18.84 & 16.01 & 54.07 & 31.62 & 66.07 & 9.66 & 4.80 & 1.88 \\
PandaGPT & 3.00 & 4.09 & 5.43 & 18.21 & 18.57 & 21.08 & 16.00 & 14.68 & 20.34 & 17.06 & 18.98 & 9.41 & 6.51 & 3.05 \\
OLA & 13.38 & 8.86 & 18.24 & 46.34 & 25.07 & 46.10 & 38.24 & 13.13 & 56.92 & 24.78 & 50.88 & 16.92 & 6.71 & 2.91 \\
\bottomrule
\end{tabular}

# Table 15 
**Audio-visual video classification results on VGGSound inputs.**

In [19]:
import pickle as pk
from vggsounder.benchmark import benchmark, get_metric_dataframe, select_metrics
from vggsounder.labels import VGGSounder


models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
vggsounder = VGGSounder(csv_path=csv_path)

vggsound_results = pk.load(open("precomputed_results/vggsound_results.pkl", "rb"))
table_15_df = get_metric_dataframe(vggsound_results, modalities=["a", "v", "av"])
table_15 = select_metrics(
    table_15_df, 
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ], 
    display_names=display_names
)
table_15

metric             accuracy                               f1             \
modality                  a          v         av          a          v
Gemini 1.5 Flash   0.310760  22.122232  23.598343   1.708132  33.154648
Gemini 1.5 Pro     1.288359  25.767189  21.306487   4.429014  36.409865
Gemini 2.0 Flash   5.703742  20.290043  19.390133   9.947751  32.344071
VideoLLaMA 2      27.981354  17.007640  21.461867  41.323123  31.461480
Unified-IO 2      32.280202  20.238249  52.395442  43.714058  33.844973
PandaGPT           5.198757   7.652467   8.947300  12.681473  16.831683
OLA               10.714748   8.630066  14.294963  23.334031  17.811464

metric                        hit_rate                               mu  \
modality                 av          a          v         av          a
Gemini 1.5 Flash  35.938382   2.978117  31.833484  41.233976   1.514955
Gemini 1.5 Pro    35.624527   6.111615  41.719539  45.701152   1.618542
Gemini 2.0 Flash  33.913692   9.491130  30.551599  35.310113   2.499029
VideoLLaMA 2      36.799180  30.046614  22.724330  27.897190  11.161466
Unified-IO 2      64.064593  33.710993  22.840865  54.195261   4.875049
PandaGPT          19.547942   8.539428  11.226207  13.297941   4.506021
OLA               28.862026  18.056455  10.954292  22.413570   7.613622

metric
modality                 v        av
Gemini 1.5 Flash  4.169364  0.090638
Gemini 1.5 Pro    5.412405  0.239544
Gemini 2.0 Flash  4.771462  0.627994
VideoLLaMA 2      2.848634  1.417843
Unified-IO 2      3.418361  0.874013
PandaGPT          4.480124  0.938754
OLA               4.052829  0.712158

In [20]:
print(table_15.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{3}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a & v & av & a & v & av \\
\midrule
Gemini 1.5 Flash & 0.31 & 22.12 & 23.60 & 1.71 & 33.15 & 35.94 & 2.98 & 31.83 & 41.23 & 1.51 & 4.17 & 0.09 \\
Gemini 1.5 Pro & 1.29 & 25.77 & 21.31 & 4.43 & 36.41 & 35.62 & 6.11 & 41.72 & 45.70 & 1.62 & 5.41 & 0.24 \\
Gemini 2.0 Flash & 5.70 & 20.29 & 19.39 & 9.95 & 32.34 & 33.91 & 9.49 & 30.55 & 35.31 & 2.50 & 4.77 & 0.63 \\
VideoLLaMA 2 & 27.98 & 17.01 & 21.46 & 41.32 & 31.46 & 36.80 & 30.05 & 22.72 & 27.90 & 11.16 & 2.85 & 1.42 \\
Unified-IO 2 & 32.28 & 20.24 & 52.40 & 43.71 & 33.84 & 64.06 & 33.71 & 22.84 & 54.20 & 4.88 & 3.42 & 0.87 \\
PandaGPT & 5.20 & 7.65 & 8.95 & 12.68 & 16.83 & 19.55 & 8.54 & 11.23 & 13.30 & 4.51 & 4.48 & 0.94 \\
OLA & 10.71 & 8.63 & 14.29 & 23.33 & 17.81 & 28.86 & 18.06 & 10.95 & 22.41 & 7.61 & 4.05 & 0.71 \\
\bottomrule
\end{tabular}

# Table 16 
**Audio-visual video classification results on VGGSound + human annotations**

In [21]:
from vggsounder.benchmark import benchmark


models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/intermediate-tables/0.4_majority_inhouse+mturk_formated.csv"
display_names = {
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
table_16 = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    dataset_path=csv_path
)
table_16

  0%|          | 0/7 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

metric             accuracy                               f1             \
modality                  a          v         av          a          v
Gemini 1.5 Flash   1.667871  14.489707  16.418688  14.421158  36.723976
Gemini 1.5 Pro     2.856392  21.317773  22.585925  19.165398  49.146085
Gemini 2.0 Flash   1.825465  12.829806  12.661806  11.746822  33.977768
VideoLLaMA 2      12.706021  19.396927  23.977087  38.374354  47.259600
Unified-IO 2      11.412437  11.648304  25.985716  34.165002  28.366349
PandaGPT           2.928623   4.269353   5.408421  17.687458  18.554328
OLA               13.316698   8.748913  18.442196  45.894388  25.215388

metric                        hit_rate                               mu  \
modality                 av          a          v         av          a
Gemini 1.5 Flash  41.927887  32.254252  46.433749  57.588157  14.629376
Gemini 1.5 Pro    52.848607  34.716659  67.251377  73.329862   3.729057
Gemini 2.0 Flash  36.001974  18.294044  42.715280  46.443982   2.770715
VideoLLaMA 2      51.589033  56.937422  50.217454  57.364975  15.516005
Unified-IO 2      48.542419  51.441329  30.523340  62.386550  10.078884
PandaGPT          20.528199  19.679559  16.526529  18.040470   9.720321
OLA               46.356712  55.762033  24.275152  50.022318  16.415672

metric
modality                 v        av
Gemini 1.5 Flash  3.983311  1.408175
Gemini 1.5 Pro    4.191929  0.723646
Gemini 2.0 Flash  5.072039  0.984419
VideoLLaMA 2      5.345850  3.070604
Unified-IO 2      4.837343  1.825412
PandaGPT          6.473695  3.057566
OLA               6.343308  2.712041

In [22]:
print(table_16.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{3}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a & v & av & a & v & av \\
\midrule
Gemini 1.5 Flash & 1.67 & 14.49 & 16.42 & 14.42 & 36.72 & 41.93 & 32.25 & 46.43 & 57.59 & 14.63 & 3.98 & 1.41 \\
Gemini 1.5 Pro & 2.86 & 21.32 & 22.59 & 19.17 & 49.15 & 52.85 & 34.72 & 67.25 & 73.33 & 3.73 & 4.19 & 0.72 \\
Gemini 2.0 Flash & 1.83 & 12.83 & 12.66 & 11.75 & 33.98 & 36.00 & 18.29 & 42.72 & 46.44 & 2.77 & 5.07 & 0.98 \\
VideoLLaMA 2 & 12.71 & 19.40 & 23.98 & 38.37 & 47.26 & 51.59 & 56.94 & 50.22 & 57.36 & 15.52 & 5.35 & 3.07 \\
Unified-IO 2 & 11.41 & 11.65 & 25.99 & 34.17 & 28.37 & 48.54 & 51.44 & 30.52 & 62.39 & 10.08 & 4.84 & 1.83 \\
PandaGPT & 2.93 & 4.27 & 5.41 & 17.69 & 18.55 & 20.53 & 19.68 & 16.53 & 18.04 & 9.72 & 6.47 & 3.06 \\
OLA & 13.32 & 8.75 & 18.44 & 45.89 & 25.22 & 46.36 & 55.76 & 24.28 & 50.02 & 16.42 & 6.34 & 2.71 \\
\bottomrule
\end{tabular}

# Table 17
**Audio-visual video classification results on VGGSound + human annotations + automatically added labels**

In [23]:
from vggsounder.benchmark import benchmark


models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}
table_17 = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("accuracy", ["a", "v", "av"]),
        ("f1",["a", "v", "av"]), 
        ("hit_rate",["a", "v", "av"]), 
        ("mu",["a", "v", "av"])
    ],
    dataset_path=csv_path
)
table_17

  0%|          | 0/7 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

metric             accuracy                               f1             \
modality                  a          v         av          a          v
Gemini 1.5 Flash   1.661304  14.351986  16.147267  14.261080  36.578915
Gemini 1.5 Pro     2.830127  20.853871  22.223875  18.902668  49.121902
Gemini 2.0 Flash   1.700703  12.329661  12.301971  11.704190  33.764375
VideoLLaMA 2      12.548427  19.636126  24.165117  38.400940  47.106621
Unified-IO 2      11.392738  11.887504  25.422090  34.107689  28.101243
PandaGPT           2.935189   4.269353   5.518780  17.605054  18.415075
OLA               13.027776   8.879385  18.356266  45.549384  24.944677

metric                        hit_rate                               mu  \
modality                 av          a          v         av          a
Gemini 1.5 Flash  41.836139  32.293650  46.825167  58.140573  14.525067
Gemini 1.5 Pro    52.796393  34.762624  68.048710  74.072146   3.657344
Gemini 2.0 Flash  35.871879  18.530435  43.135692  46.931945   2.783754
VideoLLaMA 2      51.512206  57.928951  50.572630  57.850502  15.594237
Unified-IO 2      48.248638  52.091405  30.661061  62.908144  10.078884
PandaGPT          20.427112  19.889684  16.751232  18.200074   9.785514
OLA               46.039207  56.201983  24.376631  50.368167  16.565617

metric
modality                 v        av
Gemini 1.5 Flash  3.989830  1.401656
Gemini 1.5 Pro    4.120216  0.717126
Gemini 2.0 Flash  5.006845  0.997457
VideoLLaMA 2      5.306734  3.135798
Unified-IO 2      4.791707  1.838451
PandaGPT          6.506291  3.083643
OLA               6.317231  2.718561

In [24]:
print(table_17.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrrrrrrrrrrr}
\toprule
metric & \multicolumn{3}{r}{accuracy} & \multicolumn{3}{r}{f1} & \multicolumn{3}{r}{hit_rate} & \multicolumn{3}{r}{mu} \\
modality & a & v & av & a & v & av & a & v & av & a & v & av \\
\midrule
Gemini 1.5 Flash & 1.66 & 14.35 & 16.15 & 14.26 & 36.58 & 41.84 & 32.29 & 46.83 & 58.14 & 14.53 & 3.99 & 1.40 \\
Gemini 1.5 Pro & 2.83 & 20.85 & 22.22 & 18.90 & 49.12 & 52.80 & 34.76 & 68.05 & 74.07 & 3.66 & 4.12 & 0.72 \\
Gemini 2.0 Flash & 1.70 & 12.33 & 12.30 & 11.70 & 33.76 & 35.87 & 18.53 & 43.14 & 46.93 & 2.78 & 5.01 & 1.00 \\
VideoLLaMA 2 & 12.55 & 19.64 & 24.17 & 38.40 & 47.11 & 51.51 & 57.93 & 50.57 & 57.85 & 15.59 & 5.31 & 3.14 \\
Unified-IO 2 & 11.39 & 11.89 & 25.42 & 34.11 & 28.10 & 48.25 & 52.09 & 30.66 & 62.91 & 10.08 & 4.79 & 1.84 \\
PandaGPT & 2.94 & 4.27 & 5.52 & 17.61 & 18.42 & 20.43 & 19.89 & 16.75 & 18.20 & 9.79 & 6.51 & 3.08 \\
OLA & 13.03 & 8.88 & 18.36 & 45.55 & 24.94 & 46.04 & 56.20 & 24.38 & 50.37 & 16.57 & 6.32 & 2.72 \\
\bottomrule
\end{tabular}

# Poster Tables

## Voice over

In [24]:

from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path= "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}

# no voice over
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(voice_over=False)
no_voice_over_ids = [video.video_id for video in vggsounder]


no_voice_over_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("f1",["a", "v", "av"]),
    ],
    subset_ids=no_voice_over_ids,
    dataset_path=csv_path
)
no_voice_over_table

# voice over
vggsounder.set_meta_filters(voice_over=True)
voice_over_ids = [video.video_id for video in vggsounder]


voice_over_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("f1",["a", "v", "av"]),
    ],
    subset_ids=voice_over_ids,
    dataset_path=csv_path
)
voice_over_table


diff_voice_over_table =  no_voice_over_table - voice_over_table
diff_voice_over_table

  0%|          | 0/7 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

  0%|          | 0/7 [00:00<?, ?it/s]

metric                   f1
modality                  a         v        av
Gemini 1.5 Flash -17.251452  6.817002  8.925903
Gemini 1.5 Pro   -18.163835  3.332906  2.263325
Gemini 2.0 Flash  -0.195220  7.191467  6.886394
VideoLLaMA 2       3.969227  4.971291  4.340409
Unified-IO 2       4.981597  3.777224  8.341109
PandaGPT          -3.916475 -0.187263  1.726834
OLA              -10.091284  1.686147 -2.894928

In [25]:
print(diff_voice_over_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrr}
\toprule
metric & \multicolumn{3}{r}{f1} \\
modality & a & v & av \\
\midrule
Gemini 1.5 Flash & -17.25 & 6.82 & 8.93 \\
Gemini 1.5 Pro & -18.16 & 3.33 & 2.26 \\
Gemini 2.0 Flash & -0.20 & 7.19 & 6.89 \\
VideoLLaMA 2 & 3.97 & 4.97 & 4.34 \\
Unified-IO 2 & 4.98 & 3.78 & 8.34 \\
PandaGPT & -3.92 & -0.19 & 1.73 \\
OLA & -10.09 & 1.69 & -2.89 \\
\bottomrule
\end{tabular}

## Background music

In [26]:
from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path = "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}

# no background music
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(background_music=False)
no_background_music_ids = [video.video_id for video in vggsounder]

no_background_music_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("f1", ["a", "v", "av"]),
    ],
    subset_ids=no_background_music_ids,
    dataset_path=csv_path
)
no_background_music_table

# with background music
vggsounder = VGGSounder(background_music=True) 
background_music_ids = [video.video_id for video in vggsounder]

background_music_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("f1", ["a", "v", "av"]),
    ],
    subset_ids=background_music_ids,
    dataset_path=csv_path
)
background_music_table

diff_background_music_table = no_background_music_table - background_music_table
diff_background_music_table

  0%|          | 0/7 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

  0%|          | 0/7 [00:00<?, ?it/s]

metric                   f1
modality                  a         v        av
Gemini 1.5 Flash   1.173969  2.392415  4.173242
Gemini 1.5 Pro     1.861540  3.672653  5.799092
Gemini 2.0 Flash   0.466296  1.918562  3.471032
VideoLLaMA 2       2.431225  4.620166  5.524720
Unified-IO 2       6.405868 -1.151202  4.179440
PandaGPT           5.977940  0.925743  2.745251
OLA               11.837778 -0.625064  2.873214

In [27]:
print(diff_background_music_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrr}
\toprule
metric & \multicolumn{3}{r}{f1} \\
modality & a & v & av \\
\midrule
Gemini 1.5 Flash & 1.17 & 2.39 & 4.17 \\
Gemini 1.5 Pro & 1.86 & 3.67 & 5.80 \\
Gemini 2.0 Flash & 0.47 & 1.92 & 3.47 \\
VideoLLaMA 2 & 2.43 & 4.62 & 5.52 \\
Unified-IO 2 & 6.41 & -1.15 & 4.18 \\
PandaGPT & 5.98 & 0.93 & 2.75 \\
OLA & 11.84 & -0.63 & 2.87 \\
\bottomrule
\end{tabular}

## Static Images

In [28]:
from vggsounder.benchmark import benchmark
from vggsounder.labels import VGGSounder

models_path = "../../supplimentary/models-results"
csv_path = "../../supplimentary/data/vggsounder+background-music.csv"
display_names = {
    "gemini-1.5-flash": "Gemini 1.5 Flash",
    "gemini-1.5-pro": "Gemini 1.5 Pro",
    "gemini-2.0-flash": "Gemini 2.0 Flash",
    "video-llama-2-av": "VideoLLaMA 2",
    "unified-io-2": "Unified-IO 2",
    "pandagpt": "PandaGPT",
    "ola": "OLA",
}

# static images only
vggsounder = VGGSounder(csv_path=csv_path)
vggsounder.set_meta_filters(static_image=True)
static_image_ids = [video.video_id for video in vggsounder]

static_image_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("f1", ["a", "v", "av"]),
    ],
    subset_ids=static_image_ids,
    dataset_path=csv_path
)
static_image_table

# no static images
vggsounder.set_meta_filters(static_image=False)
no_static_image_ids = [video.video_id for video in vggsounder]

no_static_image_table = benchmark(
    models_path=models_path,
    display_names=display_names,
    metrics=[
        ("f1", ["a", "v", "av"]),
    ],
    subset_ids=no_static_image_ids,
    dataset_path=csv_path
)
no_static_image_table

diff_static_image_table = no_static_image_table - static_image_table
diff_static_image_table

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['wind rustiling leaves'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(
/Users/ewriji/Desktop/work/vggsounder/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['female speech, woman someone'] will be ignored
  warnings.warn(

metric                  f1
modality                 a         v        av
Gemini 1.5 Flash  5.277933  7.313747  8.867581
Gemini 1.5 Pro    4.899848  6.864390  8.184127
Gemini 2.0 Flash -1.962523  7.108631  4.389414
VideoLLaMA 2     -4.224274  9.516781  8.564778
Unified-IO 2     -1.881191  6.188150  2.378221
PandaGPT          3.682674  4.864189  5.275184
OLA               8.235859  5.401295  7.388457

In [29]:
print(diff_static_image_table.to_latex(float_format="%.2f".__mod__))

\begin{tabular}{lrrr}
\toprule
metric & \multicolumn{3}{r}{f1} \\
modality & a & v & av \\
\midrule
Gemini 1.5 Flash & 5.28 & 7.31 & 8.87 \\
Gemini 1.5 Pro & 4.90 & 6.86 & 8.18 \\
Gemini 2.0 Flash & -1.96 & 7.11 & 4.39 \\
VideoLLaMA 2 & -4.22 & 9.52 & 8.56 \\
Unified-IO 2 & -1.88 & 6.19 & 2.38 \\
PandaGPT & 3.68 & 4.86 & 5.28 \\
OLA & 8.24 & 5.40 & 7.39 \\
\bottomrule
\end{tabular}